/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ARROW
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form secion
     */
    public menu() {
        initComponents();
         this.setExtendedState(menu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        btnMenuVerCita = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnMenuReportesDiarios = new javax.swing.JMenuItem();
        btnMenuReportesSemanal = new javax.swing.JMenuItem();
        btnMenuReportesMensual = new javax.swing.JMenuItem();
        btnMenuReportesAnual = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        btnHoras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo2.png"))); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar.png"))); // NOI18N
        jMenu2.setText(" Agregar Paciente  ");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historila2.png"))); // NOI18N
        jMenu3.setText("  Historial  ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bus.png"))); // NOI18N
        jMenuItem1.setText("Buscar Paciente ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        jMenuItem2.setText("Cita Rápida");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendar.png"))); // NOI18N
        jMenu6.setText("Citas");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_icon.png"))); // NOI18N
        jMenuItem5.setText("Agregar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        btnMenuVerCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        btnMenuVerCita.setText("Ver");
        btnMenuVerCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuVerCitaActionPerformed(evt);
            }
        });
        jMenu6.add(btnMenuVerCita);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/report.png"))); // NOI18N
        jMenu4.setText("Reportes");

        btnMenuReportesDiarios.setText("Diarios");
        btnMenuReportesDiarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuReportesDiariosActionPerformed(evt);
            }
        });
        jMenu4.add(btnMenuReportesDiarios);

        btnMenuReportesSemanal.setText("Semanal");
        btnMenuReportesSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuReportesSemanalActionPerformed(evt);
            }
        });
        jMenu4.add(btnMenuReportesSemanal);

        btnMenuReportesMensual.setText("Mensual");
        btnMenuReportesMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuReportesMensualActionPerformed(evt);
            }
        });
        jMenu4.add(btnMenuReportesMensual);

        btnMenuReportesAnual.setText("Anual");
        btnMenuReportesAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuReportesAnualActionPerformed(evt);
            }
        });
        jMenu4.add(btnMenuReportesAnual);

        jMenu6.add(jMenu4);

        jMenuBar1.add(jMenu6);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ayuda.png"))); // NOI18N
        jMenu1.setText("Ayuda");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jMenu5.setText("Cerrar Sesión");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu7.setText("Administración");

        btnHoras.setText("Horas");
        btnHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorasActionPerformed(evt);
            }
        });
        jMenu7.add(btnHoras);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
           buscar_paciente op=new buscar_paciente();
           op.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
           
        vtnregistro_paciente o= new vtnregistro_paciente();
        o.setVisible(true); 
        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        vtneditarhistorial p= new vtneditarhistorial();
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        this.dispose();
       vtnlogin in=new vtnlogin();
       in.setVisible(true);
        //System.exit(0);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        VtnAgragarCitas vtnAgragarCitas = new VtnAgragarCitas();
        vtnAgragarCitas.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnMenuReportesDiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuReportesDiariosActionPerformed
        // TODO add your handling code here:
        VtnReporteDiariosDeCitas vtnReporteDiariosDeCitas = new VtnReporteDiariosDeCitas();
        vtnReporteDiariosDeCitas.setVisible(true);
    }//GEN-LAST:event_btnMenuReportesDiariosActionPerformed

    private void btnMenuReportesSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuReportesSemanalActionPerformed
        // TODO add your handling code here:
        VtnReporteSemanalDeCitas vtnReporteSemanalDeCitas = new VtnReporteSemanalDeCitas();
        vtnReporteSemanalDeCitas.setVisible(true);
    }//GEN-LAST:event_btnMenuReportesSemanalActionPerformed

    private void btnMenuReportesMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuReportesMensualActionPerformed
        // TODO add your handling code here:
        VtnReporteMensualCitas vtnReporteMensualCitas = new VtnReporteMensualCitas();
        vtnReporteMensualCitas.setVisible(true);
    }//GEN-LAST:event_btnMenuReportesMensualActionPerformed

    private void btnMenuReportesAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuReportesAnualActionPerformed
        // TODO add your handling code here:
        VtnReporteAnualDeCitas vtnReporteAnualDeCitas = new VtnReporteAnualDeCitas();
        vtnReporteAnualDeCitas.setVisible(true);
    }//GEN-LAST:event_btnMenuReportesAnualActionPerformed

    private void btnMenuVerCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuVerCitaActionPerformed
        // TODO add your handling code here:
        VtnVerCitas vtnVerCitas = new VtnVerCitas();
        vtnVerCitas.setVisible(true);
    }//GEN-LAST:event_btnMenuVerCitaActionPerformed

    private void btnHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorasActionPerformed
        // TODO add your handling code here:
        VtnAdministracionHoras vtnAdministracionHoras = new VtnAdministracionHoras();
        vtnAdministracionHoras.setVisible(true);
    }//GEN-LAST:event_btnHorasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnHoras;
    private javax.swing.JMenuItem btnMenuReportesAnual;
    private javax.swing.JMenuItem btnMenuReportesDiarios;
    private javax.swing.JMenuItem btnMenuReportesMensual;
    private javax.swing.JMenuItem btnMenuReportesSemanal;
    private javax.swing.JMenuItem btnMenuVerCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
