/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controller.AdministracionPacientesController;
import Controller.HistorialPacienteController;
import Controller.PacienteController;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Result;
import vo.AdministracionPacientesVO;
import vo.HistorialMtsVO;
import vo.PacienteVO;

/**
 *
 * @author apple
 */
public class VtnAdministracionPacientes extends javax.swing.JFrame {

    /**
     * Variables
     */
    AdministracionPacientesController administracionPacientesController =
            new AdministracionPacientesController();
    PacienteController pacienteController = new PacienteController();
    HistorialPacienteController historialPacienteController =
            new HistorialPacienteController();
    
    /**
     * Creates new form VtnAdministracionPacientes
     */
    public VtnAdministracionPacientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.initValores();
    }
    
    public final void initValores(){
        //jtbPacientes
        String[] titulo = {
            "#",
            "Clave" ,
            "Nombre del paciente",  
            "Domicilio", 
            "Telefono", 
            "Numero de citas",
            "Ultima cita"
        };
        DefaultTableModel modelo = new DefaultTableModel(null, titulo) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, 
                java.lang.Object.class, 
                java.lang.Object.class, 
                java.lang.Object.class,
                java.lang.Object.class, 
                java.lang.Object.class, 
                java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        };
        
        
        Result<List<AdministracionPacientesVO>> result =
                administracionPacientesController.findAll();
        if(result.isOperationStatus()) {
            Object[] fila = new Object[8];
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            //String fecha = "";
            result.getResult().forEach(adm ->{
                fila[0] = false;
                fila[1] = adm.getId();
                fila[2] = adm.getNombre() + " " + adm.getApellidoPaterno() + " " +
                        adm.getApellidoMaterno();
                fila[3] = adm.getDirecion();
                fila[4] = adm.getTelefono();
                fila[5] = adm.getCitas();
                String fecha = adm.ultimaCita != null ? formatter.format(adm.ultimaCita):"";
                fila[6] = fecha;
                modelo.addRow(fila);
            });
            jtbPacientes.setModel(modelo);
        }else {
            JOptionPane.showMessageDialog(null, result.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPacientes = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Administració de pacientes");

        jtbPacientes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtbPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbPacientes);

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar32.png"))); // NOI18N
        btnEliminar.setText("Eliminar Pacientes");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(347, 347, 347)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        int resp = JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar el historial de los pacientes seleccionados");
        
        if ( resp == 0) {
            for(int row = 0; row < jtbPacientes.getRowCount(); row++){
                if ( (boolean) jtbPacientes.getValueAt(row, 0) ) {
                    int idPaciente =  Integer.parseInt(jtbPacientes.getValueAt(row, 1).toString());
                    Result<List<HistorialMtsVO>> resultHistorial =
                            historialPacienteController.delete(idPaciente);
                    Result<PacienteVO> pacienteResult = pacienteController.delete(idPaciente);
                    
                    this.initValores();
                    
                    JOptionPane.showMessageDialog(null, 
                            "Paciente -->" + pacienteResult.getMessage() + "\n" +
                            resultHistorial.getMessage()
                    );
                }
            }
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAdministracionPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAdministracionPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAdministracionPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAdministracionPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnAdministracionPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbPacientes;
    // End of variables declaration//GEN-END:variables
}
