/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controller.HistorialPacienteController;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import util.ConsultorioMedicoConst;
import util.Result;
import util.Util;
import vo.HistorialMtsData;
import vo.HistorialSintomasVO;
import vo.HistorialVO;
import vo.PacienteVO;
import vo.RecetaVO;
import vo.ReporteUltrasonicoVO;
import vo.SintomasVO;

/**
 *
 * @author Alex
 */
public class vtnAgregarHistorialPaciente extends javax.swing.JFrame {

    /**
     * Variables
     */
    PacienteVO pacienteVO = new PacienteVO();
    HistorialPacienteController historialPacienteController = 
                new HistorialPacienteController();
    
    /**
     * Creates new form vtnHistorialPaciente
     */
    public vtnAgregarHistorialPaciente() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    public vtnAgregarHistorialPaciente(PacienteVO pacienteVO) {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.pacienteVO = pacienteVO;
        this.initValores();
    }
    
    public final void initValores(){
        txtNombreCompleto.setText(pacienteVO.getNombre() + " " + 
                pacienteVO.getApellidoPaterno() + " " + 
                pacienteVO.getApellidoMaterno());
        
        int edad = new Date().getYear() - pacienteVO.getFechaNacimiento().getYear();
        
        txtEdad.setText(String.valueOf(edad));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuSintomas = new javax.swing.JPopupMenu();
        jmiEliminar = new javax.swing.JMenuItem();
        btnUpdateHistorial = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSintoma = new javax.swing.JTextField();
        btnSintomas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblSintomas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaRx = new javax.swing.JTextArea();
        txtEdad = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtTalla = new javax.swing.JTextField();
        txtFc = new javax.swing.JTextField();
        txtFr = new javax.swing.JTextField();
        txtTa = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtTemp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jDataProximaCita = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDxs = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaPlanManejo = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaParecimientoActual = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblAntecedentesImportantes = new javax.swing.JTable();
        btnagregarSintomasImportantes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txaReporteUltrasonico = new javax.swing.JTextArea();

        jmiEliminar.setText("Eliminar");
        jmiEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarActionPerformed(evt);
            }
        });
        menuSintomas.add(jmiEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnUpdateHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnUpdateHistorial.setText("Guardar");
        btnUpdateHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHistorialActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        jLabel1.setText("Nombre del paciente:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Sintomas :");

        btnSintomas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas_opc.png"))); // NOI18N
        btnSintomas.setText("Agregar");
        btnSintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSintomasActionPerformed(evt);
            }
        });

        jTblSintomas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTblSintomas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sintomas "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTblSintomas.setComponentPopupMenu(menuSintomas);
        jScrollPane1.setViewportView(jTblSintomas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnSintomas)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSintomas))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sintomas del Paciente", jPanel1);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel4.setText("Edad:");

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel5.setText("Peso:");

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel6.setText("Talla:");

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel7.setText("Temp:");

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel8.setText("FC:");

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel9.setText("FR:");

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel10.setText("T/A:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Fecha:");

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel12.setText("PRÓXIMA CITA:");

        txaRx.setColumns(20);
        txaRx.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        txaRx.setRows(5);
        jScrollPane2.setViewportView(txaRx);

        txtFc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFcActionPerformed(evt);
            }
        });

        txtTemp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel13.setText("RX:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(15, 15, 15))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFecha)
                            .addComponent(txtFr, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTemp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTa)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTalla)
                                .addComponent(txtPeso)))))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(54, 54, 54)
                        .addComponent(jDataProximaCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDataProximaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Receta Medica", jPanel2);

        jLabel17.setText("PADECIMIENTO ACTUAL :");

        jLabel18.setText("PLAN DE MANEJO :");

        jLabel19.setText("DXS :");

        txaDxs.setColumns(20);
        txaDxs.setRows(5);
        jScrollPane3.setViewportView(txaDxs);

        txaPlanManejo.setColumns(20);
        txaPlanManejo.setRows(5);
        jScrollPane5.setViewportView(txaPlanManejo);

        txaParecimientoActual.setColumns(20);
        txaParecimientoActual.setRows(5);
        jScrollPane6.setViewportView(txaParecimientoActual);

        jTblAntecedentesImportantes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTblAntecedentesImportantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Antecedentes Importantes "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTblAntecedentesImportantes);

        btnagregarSintomasImportantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas_opc.png"))); // NOI18N
        btnagregarSintomasImportantes.setText("Agregar");
        btnagregarSintomasImportantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarSintomasImportantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnagregarSintomasImportantes))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                            .addComponent(jLabel18)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6))))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnagregarSintomasImportantes))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Historial", jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        txaReporteUltrasonico.setColumns(20);
        txaReporteUltrasonico.setRows(5);
        jScrollPane7.setViewportView(txaReporteUltrasonico);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reporte de Ultrasonido ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreCompleto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateHistorial))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateHistorial)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSintomasActionPerformed

       String simtomas = txtSintoma.getText();
       
       if ( simtomas ==null || "".equals(simtomas) ) {
           JOptionPane.showMessageDialog(null,"El sintoma no puede estar vacio");
           return;
       }
       
       DefaultTableModel model = (DefaultTableModel) jTblSintomas.getModel();
       model.addRow(new Object[]{simtomas});
       
       jTblSintomas.setModel(model);
       
       txtSintoma.setText(String.valueOf(""));
                
    }//GEN-LAST:event_btnSintomasActionPerformed

    private void txtFcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFcActionPerformed

    /**
     * Metodo encargado en abrir la ventana para ver los antecedentes importantes
     * @param evt 
     */
    private void btnagregarSintomasImportantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarSintomasImportantesActionPerformed
        // TODO add your handling code here:
        VtnAntecedentesImportantes  vtnAntecedentesImportantes = 
                new VtnAntecedentesImportantes(this, true);
        vtnAntecedentesImportantes.setVisible(true);
    }//GEN-LAST:event_btnagregarSintomasImportantesActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btnUpdateHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHistorialActionPerformed
        // TODO add your handling code here:

        this.datosDumy();
        
        /**if(this.validateForm()){
            this.crearHistorial();
        }**/
        
        
    }//GEN-LAST:event_btnUpdateHistorialActionPerformed

    

    public void crearHistorial(){
        HistorialMtsData historialMtsData = new HistorialMtsData();       
        
        historialMtsData.setRecetaVO(getRecetaVO());
        historialMtsData.setHistorialVO(getHistorial());
        historialMtsData.setReporteUltrasonicoVO(getReporteUltrasonico());
        historialMtsData.setIdPaciente((int) pacienteVO.getId());
        
        java.util.Date fechaNow = new Date();
        historialMtsData.setDate(fechaNow);
        historialMtsData.setSintomasVOList(getSintomasVOs());
        
        Result<HistorialMtsData> result= historialPacienteController.add(historialMtsData);
        System.out.println(result.toString());
    }

    /**
     * =================================================================================================================
     * Validacon de los formularios
     * =================================================================================================================
     * @return
     */
    public boolean validateForm(){
        String mensage = ConsultorioMedicoConst.STRING_EMPTY;
        String sintomas = this.validateSintomas();
        String recetaMedica = this.validateRecetasMedicas();
        String historial = this.validateHistorial();
        String reporteUltrasonico = this.validateReporteUltrasonico();

        if( !ConsultorioMedicoConst.STRING_EMPTY.equals(sintomas) ){
            mensage += "Sintomas del paciente:\n";
            mensage += sintomas;
        }
        if( !ConsultorioMedicoConst.STRING_EMPTY.equals(recetaMedica) ) {
            mensage += "Receta Medica:\n";
            mensage += recetaMedica;
        }
        if( !ConsultorioMedicoConst.STRING_EMPTY.equals(historial) ) {
            mensage += "Historial:\n";
            mensage += historial;
        }
        if( !ConsultorioMedicoConst.STRING_EMPTY.equals(reporteUltrasonico) ) {
            mensage += "Reporte de Ultrasonido:\n";
            mensage += reporteUltrasonico;
        }

        if( !ConsultorioMedicoConst.STRING_EMPTY.equals(mensage) ) {
            mensage += "******* Favor los campos solicitados ********";
            JOptionPane.showMessageDialog(null,mensage);
            return false;
        }

        return true;
    }
    public String validateSintomas(){
        if ( jTblSintomas.getRowCount() < 0 ) {
            return "---->Debe de tener al menos un sintoma:\n";
        }
        return ConsultorioMedicoConst.STRING_EMPTY;
    }
    public String validateRecetasMedicas(){
        String recetaMedica = ConsultorioMedicoConst.STRING_EMPTY;
        if(!Util.validateString(txtEdad.getText())){
            recetaMedica +="---->El campo 'edad' es requediro\n";
        }else if(!Util.validateInteger(txtEdad.getText())){
            recetaMedica +="---->El campo 'edad' debe ser un valor numerico\n";
        }

        if(!Util.validateString(txtPeso.getText())){
            recetaMedica +="---->El campo 'peso' es requediro\n";
        }else if(!Util.validateFloat(txtPeso.getText())){
            recetaMedica +="---->El valor del campo 'peso' no es valido\n";
        }

        if(!Util.validateString(txtTalla.getText())){
            recetaMedica +="---->El campo 'Talla' es requediro\n";
        }else if(!Util.validateFloat(txtTalla.getText())){
            recetaMedica +="---->El valor del 'Talla' peso no es valido\n";
        }

        if(!Util.validateString(txtTemp.getText())){
            recetaMedica +="---->El campo 'Temp' es requediro\n";
        }
//        else if(!Util.validateFloat(txtTemp.getText())){
//            recetaMedica +="---->El valor del 'Temp' peso no es valido";
//        }

        if(!Util.validateString(txtFc.getText())){
            recetaMedica +="---->El campo 'Fc' es requediro\n";
        }

        if(!Util.validateString(txtFr.getText())){
            recetaMedica +="---->El campo 'Fr' es requediro\n";
        }

        if(!Util.validateString(txtTa.getText())){
            recetaMedica +="---->El campo 'T/A' es requediro\n";
        }

        if(!Util.validateString(txtFecha.getText())){
            recetaMedica +="---->El campo 'fecha' es requediro\n";
        }

        if(!Util.validateString(txaRx.getText())){
            recetaMedica +="---->El campo 'RX' es requediro\n";
        }


        return recetaMedica;
    }

    public String validateHistorial(){
        String historial = ConsultorioMedicoConst.STRING_EMPTY;

        if(!Util.validateString(txaParecimientoActual.getText())){
            historial +="---->El campo 'Parecimiento Actual' es requediro\n";
        }

        if(!Util.validateString(txaDxs.getText())){
            historial +="---->El campo 'Dxs' es requediro\n";
        }

        if(!Util.validateString(txaPlanManejo.getText())){
            historial +="---->El campo 'Plan Manejo' es requediro\n";
        }
        return historial;
    }

    public String validateReporteUltrasonico(){
        String reporteUltrasonico = ConsultorioMedicoConst.STRING_EMPTY;
        if(!Util.validateString(txaReporteUltrasonico.getText())){
            reporteUltrasonico +="---->El campo 'Reporte Ultrasonico' es requediro\n";
        }
        return reporteUltrasonico;
    }



    /**
     * =================================================================================================================
     * conversion de los formularios a objetos de negocio
     * =================================================================================================================
     * @return
     */
    public RecetaVO getRecetaVO(){
        RecetaVO recetaVO = new RecetaVO();
        recetaVO.setEdad(Integer.parseInt(txtEdad.getText()));
        recetaVO.setPeso(Float.parseFloat(txtPeso.getText()));
        recetaVO.setTalla(Float.parseFloat(txtTalla.getText()));
        recetaVO.setTemp(txtTemp.getText());
        recetaVO.setFc(txtFc.getText());
        recetaVO.setRf(txtFr.getText());
        recetaVO.setTa(txtTa.getText());
        recetaVO.setRx(txaRx.getText());
        java.util.Date fechaNow = new Date();
        recetaVO.setFecha(fechaNow);
        java.util.Date proximaxita = jDataProximaCita.getDate();
        recetaVO.setFechaProximaCita(proximaxita);
        return recetaVO;
    }
    
    public HistorialVO getHistorial(){
        HistorialVO historialVO = new HistorialVO();
        historialVO.setParecimientoActual(txaParecimientoActual.getText());
        historialVO.setDxs(txaDxs.getText());
        historialVO.setPlanManejo(txaPlanManejo.getText());
        historialVO.setHistorialSintomasVOList(getHistorialSintomasVOs());
        return historialVO;
    }
    
    public List<HistorialSintomasVO> getHistorialSintomasVOs(){
        List<HistorialSintomasVO> historialSintomasVOs = new ArrayList<HistorialSintomasVO>();
        DefaultTableModel model = (DefaultTableModel) jTblAntecedentesImportantes.getModel(); 
        int columna = 0;
        for(int row = 0; row < model.getRowCount(); row++ ) {
            String antecedenteImportante = model.getValueAt(row, columna).toString();
             historialSintomasVOs.add(new HistorialSintomasVO(antecedenteImportante));
        }
        return historialSintomasVOs;
    }
    
    public ReporteUltrasonicoVO getReporteUltrasonico(){
        ReporteUltrasonicoVO reporteUltrasonicoVO = new ReporteUltrasonicoVO();
        reporteUltrasonicoVO.setDescripcion("descripcion del reporte ultrasonico");
        return reporteUltrasonicoVO;
    }

    
    public List<SintomasVO> getSintomasVOs(){
        List<SintomasVO> sintomasVOs = new ArrayList<SintomasVO>();
        DefaultTableModel model = (DefaultTableModel) jTblSintomas.getModel(); 
        int columna = 0;
        for(int row = 0; row < model.getRowCount(); row++ ) {
            String sintoma = model.getValueAt(row, columna).toString();
             sintomasVOs.add(new SintomasVO(sintoma));
        }
        return sintomasVOs;
    }


    /**
     * =================================================================================================================
     * Datos Dumy
     * =================================================================================================================
     */
    public void datosDumy(){
        HistorialMtsData historialMtsData = new HistorialMtsData();       
        List<SintomasVO> sintomasVOs = new ArrayList<SintomasVO>();
        RecetaVO recetaVO = new RecetaVO();
        HistorialVO historialVO = new HistorialVO();
        List<HistorialSintomasVO> historialSintomasVOs = new ArrayList<HistorialSintomasVO>();
        ReporteUltrasonicoVO reporteUltrasonicoVO = new ReporteUltrasonicoVO();

        
        
        /**
         * Recetas
         */
        recetaVO.setEdad(26);
        recetaVO.setPeso(68);
        recetaVO.setTalla(1.68f);
        recetaVO.setTemp("NA");
        recetaVO.setFc("N/A");
        recetaVO.setRf("N/A");
        recetaVO.setTa("N/A");
        recetaVO.setRx("N/A");
        java.util.Date fechaNow = new Date();
        recetaVO.setFecha(fechaNow);
        recetaVO.setFechaProximaCita(fechaNow);
        historialMtsData.setRecetaVO(recetaVO);
        
        
        /**
         * Historial
         */
        historialVO.setParecimientoActual("Parecimiento actual");
        historialVO.setDxs("Dxs");
        historialVO.setPlanManejo("Plan de manejo");
        
        
          /***
         * Historial de sintomas
         */
        
        historialSintomasVOs.add(new HistorialSintomasVO("Antecente importante 1"));
        historialSintomasVOs.add(new HistorialSintomasVO("Antecente importante 2"));
        historialSintomasVOs.add(new HistorialSintomasVO("Antecente importante 3"));
        historialSintomasVOs.add(new HistorialSintomasVO("Antecente importante 4"));
        historialSintomasVOs.add(new HistorialSintomasVO("Antecente importante 5"));
        historialVO.setHistorialSintomasVOList(historialSintomasVOs);
        
        
        
        historialMtsData.setHistorialVO(historialVO);
        
        
      
        
        
        
        /**
         * Reporte ultrasonico
         */
        reporteUltrasonicoVO.setDescripcion("descripcion del reporte ultrasonico");
        historialMtsData.setReporteUltrasonicoVO(reporteUltrasonicoVO);

        
        /**
         * Sintomas
         */
        sintomasVOs.add(new SintomasVO("Sintoma 1"));
        sintomasVOs.add(new SintomasVO("Sintoma 2"));
        sintomasVOs.add(new SintomasVO("Sintoma 3"));
        sintomasVOs.add(new SintomasVO("Sintoma 4"));
        sintomasVOs.add(new SintomasVO("Sintoma 5"));       
        historialMtsData.setSintomasVOList(sintomasVOs);
        
        /**
         * Id del paciente
         */
        historialMtsData.setIdPaciente((int) pacienteVO.getId());
        
        /**
         * Fecha
         */
        historialMtsData.setDate(fechaNow);
        
        
        
        Result<HistorialMtsData> result= historialPacienteController.add(historialMtsData);
        System.out.println(result.toString());
    }
    
    
    private void jmiEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarActionPerformed
        // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel) jTblSintomas.getModel(); 
       model.removeRow( jTblSintomas.getSelectedRow() );
       jTblSintomas.setModel(model);
    }//GEN-LAST:event_jmiEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnAgregarHistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnAgregarHistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnAgregarHistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnAgregarHistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnAgregarHistorialPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSintomas;
    private javax.swing.JButton btnUpdateHistorial;
    private javax.swing.JButton btnagregarSintomasImportantes;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDataProximaCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTblAntecedentesImportantes;
    private javax.swing.JTable jTblSintomas;
    private javax.swing.JMenuItem jmiEliminar;
    private javax.swing.JPopupMenu menuSintomas;
    private javax.swing.JTextArea txaDxs;
    private javax.swing.JTextArea txaParecimientoActual;
    private javax.swing.JTextArea txaPlanManejo;
    private javax.swing.JTextArea txaReporteUltrasonico;
    private javax.swing.JTextArea txaRx;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFc;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFr;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtSintoma;
    private javax.swing.JTextField txtTa;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}