/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controller.HistorialPacienteController;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.StringTokenizer;
import javax.swing.table.DefaultTableModel;
import util.Result;
import vo.HistorialMtsData;
import vo.HistorialMtsVO;
import vo.HistorialSintomasVO;
import vo.HistorialVO;
import vo.PacienteVO;
import vo.RecetaVO;
import vo.ReporteUltrasonicoVO;
import vo.SintomasVO;

/**
 *
 * @author Alex
 */
public class vtnVerHistorialPaciente extends javax.swing.JFrame {

    /**
     * Variables
     */
    PacienteVO pacienteVO = new PacienteVO();
    Map<String, HistorialMtsVO> listHistorial = new HashMap();
     HistorialPacienteController historialPacienteController = 
                new HistorialPacienteController();
    boolean isOperationSearchHistory;
            
    /**
     * Creates new form vtnHistorialPaciente
     */
    public vtnVerHistorialPaciente() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    public vtnVerHistorialPaciente(PacienteVO pacienteVO) {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.pacienteVO = pacienteVO;
        txtNombreCompleto.setText(pacienteVO.getNombre() + " " + 
                pacienteVO.getApellidoPaterno() + " " + 
                pacienteVO.getApellidoMaterno());
        
        this.getHistorialConsulta();
        txtEdad.setEditable(false);
        txtPeso.setEditable(false);
        txtFc.setEditable(false);
        txtFr.setEditable(false);
        txtTa.setEditable(false);
        txtTalla.setEditable(false);
        txtTemp.setEditable(false);
        txaRx.setEditable(false);
        txaDxs.setEditable(false);
        txaParecimientoActual.setEditable(false);
        txaPlanManejo.setEditable(false);
        txaReporteUltrasonico.setEditable(false);
        jDataProximaCita.setEnabled(false);
    }
    
    public final void getHistorialConsulta(){        
        Result<List<HistorialMtsVO>> result =
                historialPacienteController.getHistorialPacienteByIdPaciente( 
                    (int) pacienteVO.getId()
                );
        
        
        
        int i = 0;
        listHistorial.clear();

        for ( HistorialMtsVO historialMtsVO: result.getResult() ) {
            i++;
            listHistorial.put(String.valueOf(i), historialMtsVO);
        }
        setFechasConsulta();
    }
    
    
    public void setFechasConsulta(){
        jcbFechaConsultas.removeAllItems();
        jcbFechaConsultas.removeAll();
        jcbFechaConsultas.addItem("0" + ": " + "Seleccione un consulta");
        String fecha;
        SimpleDateFormat formatoLargoEsMX = new SimpleDateFormat(
            "EEEE d 'de' MMMM 'de' yyyy", new Locale("ES", "MX")
         );
        for ( Map.Entry<String, HistorialMtsVO> m: listHistorial.entrySet() ) {
            fecha = formatoLargoEsMX.format( m.getValue().getFecha());
             jcbFechaConsultas.addItem( m.getKey()+ ": " + fecha);
        }
        isOperationSearchHistory = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblSintomas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaRx = new javax.swing.JTextArea();
        txtEdad = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtTalla = new javax.swing.JTextField();
        txtFc = new javax.swing.JTextField();
        txtFr = new javax.swing.JTextField();
        txtTa = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtTemp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jDataProximaCita = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDxs = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaPlanManejo = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaParecimientoActual = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblAntecedentesImportantes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txaReporteUltrasonico = new javax.swing.JTextArea();
        jcbFechaConsultas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Fechas de consulta:");

        jTblSintomas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTblSintomas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Sintomas "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTblSintomas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sintomas del Paciente", jPanel1);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel4.setText("Edad:");

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel5.setText("Peso:");

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel6.setText("Talla:");

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel7.setText("Temp:");

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel8.setText("FC:");

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel9.setText("FR:");

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel10.setText("T/A:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Fecha:");

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel12.setText("PRÓXIMA CITA:");

        txaRx.setColumns(20);
        txaRx.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        txaRx.setRows(5);
        jScrollPane2.setViewportView(txaRx);

        txtFc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFcActionPerformed(evt);
            }
        });

        txtTemp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel13.setText("RX:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(15, 15, 15))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFecha)
                            .addComponent(txtFr, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTemp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTa)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTalla)
                                .addComponent(txtPeso)))))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(54, 54, 54)
                        .addComponent(jDataProximaCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDataProximaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Receta Medica", jPanel2);

        jLabel16.setText("ANTECEDENTES DE IMPORTANCIA :");

        jLabel17.setText("PADECIMIENTO ACTUAL :");

        jLabel18.setText("PLAN DE MANEJO :");

        jLabel19.setText("DXS :");

        txaDxs.setColumns(20);
        txaDxs.setRows(5);
        jScrollPane3.setViewportView(txaDxs);

        txaPlanManejo.setColumns(20);
        txaPlanManejo.setRows(5);
        jScrollPane5.setViewportView(txaPlanManejo);

        txaParecimientoActual.setColumns(20);
        txaParecimientoActual.setRows(5);
        jScrollPane6.setViewportView(txaParecimientoActual);

        jTblAntecedentesImportantes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTblAntecedentesImportantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Sintomas "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTblAntecedentesImportantes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(27, 27, 27)
                            .addComponent(jScrollPane4))
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel16)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Historial", jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        txaReporteUltrasonico.setColumns(20);
        txaReporteUltrasonico.setRows(5);
        jScrollPane7.setViewportView(txaReporteUltrasonico);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reporte de Ultrasonido ", jPanel3);

        jcbFechaConsultas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbFechaConsultas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbFechaConsultasItemStateChanged(evt);
            }
        });

        jLabel2.setText("Nombre Completo:");

        txtNombreCompleto.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbFechaConsultas, 0, 680, Short.MAX_VALUE)
                            .addComponent(txtNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreCompleto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbFechaConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFcActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jcbFechaConsultasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbFechaConsultasItemStateChanged
        // TODO add your handling code here:
       
        if ( jcbFechaConsultas.getItemCount() > 0 && isOperationSearchHistory) {
            String historialSeleccionado = jcbFechaConsultas.getSelectedItem().toString();
            StringTokenizer st = new StringTokenizer(historialSeleccionado, ":");

            if(st.hasMoreElements()){
                 String idHistorialSeleccionado = st.nextElement().toString();

                 if ( !"0".equalsIgnoreCase(idHistorialSeleccionado)){
                    HistorialMtsVO historialMtsVO = listHistorial.get(idHistorialSeleccionado);

                    Result<HistorialMtsData> result = 
                            historialPacienteController.getHistorialPaciente(historialMtsVO);
                    
                    HistorialMtsData historialMtsData =  result.getResult();
                    llenarSintomas(historialMtsData.getSintomasVOList());
                    llenarRecetaMedica(historialMtsData.getRecetaVO());
                    llenarHistorial(historialMtsData.getHistorialVO());
                    llenarReporteUltrasonico(historialMtsData.getReporteUltrasonicoVO());
                 }else{
                     limpiarAntecedentesImportantes();
                     limpiarHistorial();
                     limpiarRecetaMedica();
                     limpiarReporteUltrasonico();
                     limpiarSintomas();
                 }
            }           
        }        
    }//GEN-LAST:event_jcbFechaConsultasItemStateChanged

    @SuppressWarnings("empty-statement")
    public void llenarSintomas(List<SintomasVO> sintomasVOList) {
        String[] titulo = {
            "Sintoma"
        };
        DefaultTableModel modelo = new DefaultTableModel(null, titulo);;
        if (sintomasVOList != null && !sintomasVOList.isEmpty()) {

            Object[] fila = new Object[8];
            for (SintomasVO pacienteVO : sintomasVOList) {
                fila[0] = pacienteVO.getSintomas();
                modelo.addRow(fila);
            }
            jTblSintomas.setModel(modelo);
        }else{
            Object[] fila = new Object[8];
            fila[0] = "No hay sintomas";
            modelo.addRow(fila);
            jTblSintomas.setModel(modelo);
        }
    }
    public void limpiarSintomas() {
        String[] titulo = {
            "Sintoma"
        };
        DefaultTableModel modelo = new DefaultTableModel(null, titulo);;
        Object[] fila = new Object[8];
        fila[0] = "";
        modelo.addRow(fila);
        jTblSintomas.setModel(modelo);
    }
    
    public void llenarRecetaMedica(RecetaVO recetaVO){
        if(recetaVO != null){
            txtEdad.setText(String.valueOf(recetaVO.getEdad()));
            txtPeso.setText(String.valueOf(recetaVO.getPeso()));
            txtTalla.setText(String.valueOf(recetaVO.getTalla()));
            txtTemp.setText(String.valueOf(recetaVO.getTemp()));
            txtFc.setText(String.valueOf(recetaVO.getFc()));
            txtFr.setText(String.valueOf(recetaVO.getRf()));
            txtTa.setText(String.valueOf(recetaVO.getTa()));

            SimpleDateFormat formatoLargoEsMX = new SimpleDateFormat(
                "dd/MM/yyyy"
             );
            String fecha = formatoLargoEsMX.format( recetaVO.getFecha());
            
            txtFecha.setText(String.valueOf(fecha));
            txaRx.setText(String.valueOf(recetaVO.getRx()));
            jDataProximaCita.setDate(recetaVO.getFechaProximaCita());

        }
    }   
    
    public void limpiarRecetaMedica(){
        txtEdad.setText(String.valueOf(""));
        txtPeso.setText(String.valueOf(""));
        txtTalla.setText(String.valueOf(""));
        txtTemp.setText(String.valueOf(""));
        txtFc.setText(String.valueOf(""));
        txtFr.setText(String.valueOf(""));
        txtTa.setText(String.valueOf(""));
        txtFecha.setText(null);
        txaRx.setText(String.valueOf(""));
        jDataProximaCita.setDate(null);
    } 
    
    
    public void llenarHistorial(HistorialVO historialVO){
        txaParecimientoActual.setText(String.valueOf(historialVO.getParecimientoActual()));
        txaDxs.setText(String.valueOf(historialVO.getDxs()));
        txaPlanManejo.setText(String.valueOf(historialVO.getPlanManejo()));
        llenarAntecedentesImportantes(historialVO.getHistorialSintomasVOList());
    }
    
    public void limpiarHistorial(){
        txaParecimientoActual.setText(String.valueOf(""));
        txaDxs.setText(String.valueOf(""));
        txaPlanManejo.setText(String.valueOf(""));
        limpiarAntecedentesImportantes();
    }
    
    public void llenarAntecedentesImportantes(List<HistorialSintomasVO> historialSintomasVOList){
        jTblAntecedentesImportantes.removeAll();
        String[] titulo = {
            "Antecedentes Importantes"
        };
        DefaultTableModel modelo = new DefaultTableModel(null, titulo);;

        if (historialSintomasVOList != null && !historialSintomasVOList.isEmpty()) {

            Object[] fila = new Object[8];
            for (HistorialSintomasVO historialSintomasVO : historialSintomasVOList) {
                fila[0] = historialSintomasVO.getAntecedenteImportante();
                modelo.addRow(fila);
            }
            jTblAntecedentesImportantes.setModel(modelo);
        }else{
            Object[] fila = new Object[8];
            fila[0] = "No hay Antecedentes Importantes";
            modelo.addRow(fila);
            jTblAntecedentesImportantes.setModel(modelo);
        }
    }
    
    public void limpiarAntecedentesImportantes(){
        jTblAntecedentesImportantes.removeAll();
        String[] titulo = {
            "Antecedentes Importantes"
        };
        DefaultTableModel modelo = new DefaultTableModel(null, titulo);;
        Object[] fila = new Object[8];
        fila[0] = "";
        modelo.addRow(fila);
        jTblAntecedentesImportantes.setModel(modelo);
    }
    
    public void llenarReporteUltrasonico(ReporteUltrasonicoVO reporteUltrasonicoVO){
        txaReporteUltrasonico.setText(String.valueOf(reporteUltrasonicoVO.getDescripcion()));
    }
    
    public void limpiarReporteUltrasonico(){
        txaReporteUltrasonico.setText(String.valueOf(""));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnVerHistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnVerHistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnVerHistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnVerHistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnVerHistorialPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDataProximaCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTblAntecedentesImportantes;
    private javax.swing.JTable jTblSintomas;
    private javax.swing.JComboBox jcbFechaConsultas;
    private javax.swing.JTextArea txaDxs;
    private javax.swing.JTextArea txaParecimientoActual;
    private javax.swing.JTextArea txaPlanManejo;
    private javax.swing.JTextArea txaReporteUltrasonico;
    private javax.swing.JTextArea txaRx;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFc;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFr;
    private javax.swing.JLabel txtNombreCompleto;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTa;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
